services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: admin # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: admin # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: socialweb # The PostgreSQL default database (automatically created at first launch)

    restart: always
    volumes:
      # In this example, we share the folder `db-data` in our root repository, with the default PostgreSQL data path
      # It means that every time the repository is modifying the data inside
      # of `/var/lib/postgresql/data/`, automatically the change will appear in `db-data`
      # You don't need to create the `db-data` folder. Docker Compose will do it for you
      - postgres:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    restart: always
    ports:
      - 8080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - database
volumes:
  pgadmin:
  postgres:
  # server:
  #   image: social-web-service
  #   restart: always
  #   ports:
  #     - 8000:8000
  #   environment:
  #     - DATABASE_URL=postgres://admin:admin@host.docker.internal/socialweb
  #     - JWT_SIGN_PRIVATE_KEY=password
